version: '3.5'

services:

  #
  # Приложение php-fpm с возможностью входа в bash
  # docker-compose exec app bash
  #
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./code:/var/www:delegated
      - ./composer:/home/sammy/.composer:delegated
    networks:
      - backend

  #
  # Nginx контейнер, собирается напрямую из образа
  #
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - app
      - db
    volumes:
      - ./code:/var/www:delegated
      - ./nginx/log:/var/log/nginx:delegated
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  #
  # PostgreSQL Основной контейнер с рабочей базой
  #
  db:
    image: postgres:12
    shm_size: '512m'
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=docker
    volumes:
      - ./db/data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
